### ISSUE TITLE
Multi-cursor

### ISSUE THREAD

**Issue by d0ob** [HughWen/magic-comment#6]
Hi there ! 

It doesn't work with multi-cursor, is it normal or just on my side ? Would it be possible, or is it not ? 
Would be super useful ! Thanks for the extension, in any case, love it ! And works like a charm.

**Comment by d0ob** [comment]
Also, could the extension ignore empty lines ?

**Comment by markwwen** [comment]
Hi d0ob, sorry for replying so late.
 I have fixed the the multi-cursor problem in version 1.1.0 and thanks your advise, the empty lines will be ignore now.
Hope that it can be helpful to you 😄 .

**Comment by d0ob** [comment]
Hi !
No problem, I became used to it ^^ ; But now it’s fire ! Working fine, it’s really nice ! =D 
Thanks much ! And well done =)
